#!/bin/sh

FILE=envoy.yaml

ENVOY_ADMIN_PORT=9901
sed -i 's/ENVOY_ADMIN_PORT/'$ENVOY_ADMIN_PORT'/g' $FILE

ENVOY_ADMIN_ADDRESS=127.0.0.1
sed -i 's/ENVOY_ADMIN_ADDRESS/'$ENVOY_ADMIN_ADDRESS'/g' $FILE

GRPC_SERVICE_PORT=8080
sed -i 's/GRPC_SERVICE_PORT/'$GRPC_SERVICE_PORT'/g' $FILE

GRPC_SERVICE_ADDRESS=127.0.0.1
sed -i 's/GRPC_SERVICE_ADDRESS/'$GRPC_SERVICE_ADDRESS'/g' $FILE

GRPC_WEB_PORT=8082
sed -i 's/GRPC_WEB_PORT/'$GRPC_WEB_PORT'/g' $FILE

GRPC_WEB_ADDRESS=0.0.0.0
sed -i 's/GRPC_WEB_ADDRESS/'$GRPC_WEB_ADDRESS'/g' $FILE

exec envoy -c $FILE